

[project]
name = "mt-linked-lList"
version = "0.1.0"
authors = [
    { name="Marcus E. Turnbo", email="marcus@emarcus.com" },
]
description = "A linked list module."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "hatchling>=1.32.0",
    "pytest>=9.1.1",
]
